# Generated by Django 5.1.4 on 2025-01-22 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0003_postoffice_village_post_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name='জেলা')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name='ইউনিয়ন')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা')),
                ('word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.word', verbose_name='ওয়ার্ড')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.post', verbose_name='পদবী')),
            ],
            options={
                'verbose_name': ' ওয়ারিশ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name='জেলা')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name='ইউনিয়ন')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.post', verbose_name='পদবী')),
            ],
            options={
                'verbose_name': ' ওয়ারিশ',
                'ordering': ['serial'],
            },
        ),
    ]
