# Generated by Django 5.2 on 2025-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['serial'], 'verbose_name': 'সদস্য', 'verbose_name_plural': 'সদস্য'},
        ),
        migrations.AddField(
            model_name='chairman',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='দায়িত্বরত কিনা?'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='দায়িত্বরত কিনা?'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='দায়িত্বরত কিনা?'),
        ),
    ]
