# Generated by Django 5.1.5 on 2025-04-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ward',
        ),
        migrations.AddField(
            model_name='member',
            name='ward',
            field=models.ManyToManyField(blank=True, null=True, to='region.ward', verbose_name='ওয়ার্ড'),
        ),
    ]
