# Generated by Django 5.1.4 on 2025-01-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairman',
            options={'ordering': ['serial'], 'verbose_name': 'চেয়ারম্যান', 'verbose_name_plural': 'চেয়ারম্যান'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['serial'], 'verbose_name': 'মেম্বার', 'verbose_name_plural': 'মেম্বার'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name_en'], 'verbose_name': 'পদবী', 'verbose_name_plural': 'পদবী'},
        ),
    ]
