# Generated by Django 5.1.4 on 2025-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_chairman_is_active_member_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chairman',
            options={'ordering': ['serial'], 'verbose_name': 'চেয়ারম্যান/মেয়র/প্রশাসক', 'verbose_name_plural': 'চেয়ারম্যান/মেয়র/প্রশাসক'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['serial'], 'verbose_name': 'মেম্বার/কমিশনার/কাউন্সেলর', 'verbose_name_plural': 'মেম্বার/কমিশনার/কাউন্সেলর'},
        ),
        migrations.AlterModelOptions(
            name='secretary',
            options={'ordering': ['serial'], 'verbose_name': 'কর্মকর্তা/সচিব/প্রশাসনিক কর্মকর্তা', 'verbose_name_plural': 'কর্মকর্তা/সচিব/প্রশাসনিক কর্মকর্তা'},
        ),
    ]
