# Generated by Django 5.1.5 on 2025-07-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_member_options_chairman_is_active_and_more'),
        ('account', '0002_remove_member_ward_member_ward'),
    ]

    operations = [
    ]
