# Generated by Django 5.1.4 on 2025-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_chairman_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='word',
        ),
    ]
