# Generated by Django 5.1.4 on 2025-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_chairman_options_alter_member_options_and_more'),
        ('region', '0012_delete_importantlinks_remove_uniondetails_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ward',
        ),
        migrations.AddField(
            model_name='member',
            name='ward',
            field=models.ManyToManyField(blank=True, null=True, to='region.ward', verbose_name='ওয়ার্ড'),
        ),
    ]
