# Generated by Django 5.1.5 on 2025-07-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_merge_20250701_1135'),
        ('region', '0006_uniondetails_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='ward',
        ),
        migrations.AddField(
            model_name='member',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward', verbose_name='ওয়ার্ড'),
        ),
    ]
