# Generated by Django 5.1.4 on 2025-01-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_member_word'),
        ('region', '0004_remove_word_union_remove_village_word_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward', verbose_name='ওয়ার্ড'),
        ),
    ]
