# Generated by Django 5.1.4 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_member_ward_member_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_preserved',
            field=models.BooleanField(default=False),
        ),
    ]
