# Generated by Django 5.1.4 on 2025-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ছবি'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='স্বাক্ষর'),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ছবি'),
        ),
        migrations.AddField(
            model_name='member',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='স্বাক্ষর'),
        ),
    ]
