# Generated by Django 5.1.4 on 2025-03-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_chairman_image_chairman_signature_member_image_and_more'),
        ('region', '0006_ward_ward_no_en_alter_ward_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='ছবি')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='স্বাক্ষর')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name='জেলা')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.post', verbose_name='পদবী')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name='ইউনিয়ন')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা')),
            ],
            options={
                'verbose_name': 'সচিব',
                'verbose_name_plural': 'সচিব',
                'ordering': ['serial'],
            },
        ),
    ]
