# Generated by Django 5.1.4 on 2025-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=' ই-মেইল(ইংরেজিতে)'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name=' মোবাইল'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=' ই-মেইল(ইংরেজিতে)'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name=' মোবাইল'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=' ই-মেইল(ইংরেজিতে)'),
        ),
        migrations.AddField(
            model_name='secretary',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name=' মোবাইল'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='name',
            field=models.CharField(max_length=250, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='name_en',
            field=models.CharField(max_length=250, verbose_name=' নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=250, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name_en',
            field=models.CharField(max_length=250, verbose_name=' নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='name',
            field=models.CharField(max_length=250, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='name_en',
            field=models.CharField(max_length=250, verbose_name=' নাম(ইংরেজিতে)'),
        ),
    ]
