# Generated by Django 5.1.4 on 2025-11-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0012_delete_importantlinks_remove_uniondetails_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'লিংকসমূহ',
                'verbose_name_plural': 'লিংকসমূহ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='UnionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ইউনিয়ন বা পৌরসভার ধরণ ',
                'verbose_name_plural': 'ইউনিয়ন বা পৌরসভার ধরণ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='UnionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_short', models.CharField(blank=True, max_length=50, null=True)),
                ('name_short_en', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_opacity', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('logo_opacity_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('monogram', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('monogram_en', models.FileField(blank=True, null=True, upload_to='media/logo')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district')),
                ('post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla')),
                ('union_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='union.uniontype')),
            ],
            options={
                'verbose_name': 'ইউনিয়ন বা পৌরসভা বিবরণ',
                'verbose_name_plural': 'ইউনিয়ন বা পৌরসভা বিবরণ',
                'ordering': ['name_en'],
            },
        ),
    ]
