# Generated by Django 5.1.4 on 2025-11-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=100, unique=True)),
                ('body', models.CharField(blank=True, max_length=50, null=True)),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('card', models.CharField(blank=True, max_length=50, null=True)),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=50, null=True)),
                ('navitem', models.CharField(blank=True, max_length=50, null=True)),
                ('navbar_collaps', models.CharField(blank=True, max_length=50, null=True)),
                ('member_registration', models.CharField(blank=True, max_length=50, null=True)),
                ('internal', models.CharField(blank=True, max_length=50, null=True)),
                ('other_text', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('union_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='union.uniondetails')),
            ],
        ),
    ]
