# Generated by Django 5.1.4 on 2025-11-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0002_colorroot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorroot',
            options={'ordering': ['serial'], 'verbose_name': 'কালারসমূহ', 'verbose_name_plural': 'কালারসমূহ'},
        ),
    ]
