# Generated by Django 5.1.4 on 2025-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0003_alter_colorroot_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='union_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
