# Generated by Django 5.1.4 on 2025-11-26 14:20

# import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0004_uniondetails_union_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorroot',
            name='shape',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
