# Generated by Django 5.1.4 on 2025-11-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0005_colorroot_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorroot',
            name='shape',
        ),
    ]
