# Generated by Django 5.1.4 on 2025-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0006_remove_colorroot_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorroot',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
