# Generated by Django 5.1.4 on 2025-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0007_alter_colorroot_title_alter_colorroot_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorroot',
            name='body',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='card',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='internal',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='member_registration',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='navbar_collaps',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='navitem',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='other_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='colorroot',
            name='weather',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
