# Generated by Django 5.2.8 on 2025-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0008_alter_colorroot_body_alter_colorroot_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('developer_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/developer')),
                ('monogram', models.FileField(blank=True, null=True, upload_to='media/developer')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
