# Generated by Django 5.2 on 2025-04-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateway',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Type',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='PaymentURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Payment Url',
                'verbose_name_plural': 'Payment Url',
            },
        ),
        migrations.CreateModel(
            name='PaymentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('certificate_type_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('title_en', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=500, null=True)),
                ('cause', models.CharField(blank=True, max_length=500, null=True)),
                ('cause_en', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=False)),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymenttype')),
            ],
            options={
                'verbose_name': 'Payment Purpose',
                'verbose_name_plural': 'Payment Purpose',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('nid', models.EmailField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=15, unique=True)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=55, null=True)),
                ('bank_tran_id', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(max_length=55)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_brand', models.CharField(max_length=15)),
                ('card_issuer_country', models.CharField(max_length=55)),
                ('card_issuer_country_code', models.CharField(max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(max_length=155)),
                ('verify_sign_sha2', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=15)),
                ('risk_title', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tran_purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymentpurpose')),
            ],
        ),
    ]
