# Generated by Django 5.1.4 on 2025-01-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tracking_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
