# Generated by Django 5.1.4 on 2025-01-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_transaction_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpurpose',
            name='payment_type',
        ),
    ]
