# Generated by Django 5.1.4 on 2025-01-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_paymentpurpose_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentpurpose',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.paymenttype'),
        ),
    ]
