# Generated by Django 5.1.4 on 2025-04-12 09:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('payment', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'কারণ',
                'verbose_name_plural': 'কারণ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250)),
                ('amount', models.IntegerField(default=10)),
                ('template', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ' সনদের ধরণ',
                'verbose_name_plural': ' সনদের ধরণ',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'লিঙ্গ',
                'verbose_name_plural': 'লিঙ্গ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='মন্তব্য')),
            ],
            options={
                'verbose_name': ' ওয়ারিশ',
                'verbose_name_plural': ' ওয়ারিশগণ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'সম্পর্ক',
                'verbose_name_plural': 'সম্পর্ক',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('holding_no', models.CharField(blank=True, max_length=50, null=True, verbose_name=' হোল্ডিং নং')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name=' জেলা ')),
                ('mouja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.mouja', verbose_name='মৌজা')),
                ('post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice', verbose_name='ডাকঘর ')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name=' ইউনিয়ন ')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা ')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.village', verbose_name=' গ্রাম/মহল্লা')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward', verbose_name='ওয়ার্ড নং ')),
            ],
            options={
                'verbose_name': 'ঠিকানা',
                'verbose_name_plural': 'ঠিকানা',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='নাম(বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='নাম (ইংরেজিতে)')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ইমেইল(যদি থাকে)')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল নং')),
                ('nid', models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র')),
                ('passport', models.CharField(blank=True, max_length=17, null=True, verbose_name='পাসপোর্ট নং')),
                ('father_name', models.CharField(max_length=500, verbose_name='বাবার নাম(বাংলায়)')),
                ('father_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='বাবার নাম(ইংরেজিতে)')),
                ('mother_name', models.CharField(max_length=500, verbose_name='মায়ের নাম(বাংলায়)')),
                ('mother_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)')),
                ('memorial_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='স্মারক নং')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='বিবিধ')),
                ('dob', models.DateField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='বর্ণনাঃ')),
                ('caste', models.CharField(blank=True, max_length=500, null=True, verbose_name='সম্প্রদায়')),
                ('profession', models.CharField(blank=True, max_length=500, null=True, verbose_name='পেশা')),
                ('income', models.CharField(blank=True, max_length=500, null=True, verbose_name='আয়')),
                ('amount', models.CharField(blank=True, max_length=10, null=True, verbose_name='পরিমাণ')),
                ('date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/member_file/%Y', verbose_name='মেম্বারের সুপারিশ ফাইল')),
                ('nid_file', models.FileField(blank=True, null=True, upload_to='media/nid_file/%Y', verbose_name='এনআইডি-জন্ম নিবন্ধন')),
                ('tracking_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='ট্র্যাকিং নং')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ভেরিফাইড কিনা?')),
                ('language', models.CharField(blank=True, max_length=250, null=True, verbose_name='ভাষা')),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.adress', verbose_name='ঠিকানা')),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.cause', verbose_name='কারণঃ')),
                ('chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chairman', verbose_name='চেয়ারম্যান')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.member', verbose_name='সদস্য')),
                ('others_adress', models.ManyToManyField(blank=True, to='region.othersadress', verbose_name='অন্যান্য এলাকাভুক্ত ঠিকানা')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction', verbose_name='ট্রান্সেকশন')),
                ('certificate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certificatetype', verbose_name='সনদের ধরণ')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.gender', verbose_name='লিঙ্গ')),
                ('person', models.ManyToManyField(blank=True, to='certificate.person', verbose_name='ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ')),
            ],
            options={
                'verbose_name': 'সনদসমূহ',
                'verbose_name_plural': 'সনদসমূহ',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.relation', verbose_name='সম্পর্ক'),
        ),
    ]
