# Generated by Django 5.1.4 on 2025-01-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='session_key',
        ),
        migrations.AddField(
            model_name='certificate',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
