# Generated by Django 5.1.4 on 2025-01-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_remove_certificate_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='upazilla',
        ),
        migrations.RemoveField(
            model_name='division',
            name='district',
        ),
        migrations.RemoveField(
            model_name='upazilla',
            name='union',
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.division'),
        ),
        migrations.AddField(
            model_name='union',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.upazilla'),
        ),
        migrations.AddField(
            model_name='upazilla',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.district'),
        ),
    ]
