# Generated by Django 5.2 on 2025-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_person_tracking_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['serial'], 'verbose_name': ' ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ', 'verbose_name_plural': ' ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ'},
        ),
    ]
