# Generated by Django 5.1.4 on 2025-04-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_certificate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ট্র্যাকিং নং'),
        ),
    ]
