# Generated by Django 5.1.4 on 2025-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_remove_district_upazilla_remove_division_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='village_or_house',
            new_name='holding_no',
        ),
        migrations.AddField(
            model_name='adress',
            name='village',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
