# Generated by Django 5.1.4 on 2025-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_person_tracking_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['serial'], 'verbose_name': 'ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ', 'verbose_name_plural': 'ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='মন্তব্য'),
        ),
    ]
