# Generated by Django 5.2 on 2025-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['serial'], 'verbose_name': ' ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ ', 'verbose_name_plural': ' ব্যক্তি/ওয়ারিশগণ/অন্যান্য ব্যক্তিবর্গ'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='মন্তব্য'),
        ),
    ]
