# Generated by Django 5.1.4 on 2025-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_person_options_certificate_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'ordering': ['name'], 'verbose_name': ' সনদের ধরণ', 'verbose_name_plural': ' সনদের ধরণ'},
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='is_auto_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='is_join_sign',
            field=models.BooleanField(default=False),
        ),
    ]
