# Generated by Django 5.2 on 2025-05-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0004_alter_person_options_certificate_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'ordering': ['name'], 'verbose_name': ' সনদের ধরণ', 'verbose_name_plural': ' সনদের ধরণ'},
        ),
    ]
