# Generated by Django 5.1.4 on 2025-05-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificatetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচয়পত্র'),
        ),
    ]
