# Generated by Django 5.2 on 2025-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificatetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='is_auto_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='is_join_sign',
            field=models.BooleanField(default=False),
        ),
    ]
