# Generated by Django 5.2 on 2025-05-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_certificatetype_is_auto_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র'),
        ),
    ]
