# Generated by Django 5.1.4 on 2025-01-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0006_alter_warishancertificate_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['serial'], 'verbose_name': 'ঠিকানা'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['serial'], 'verbose_name': 'সম্পর্ক'},
        ),
        migrations.AlterModelOptions(
            name='warish',
            options={'ordering': ['serial'], 'verbose_name': ' ওয়ারিশ'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.district', verbose_name=' জেলা '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='holding_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' হোল্ডিং নং'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='post_office',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ডাকঘর '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.union', verbose_name=' ইউনিয়ন '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.upazilla', verbose_name='উপজেলা '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='village',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=' গ্রাম/মহল্লা'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='word_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ওয়ার্ড নং '),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name_en',
            field=models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='serial',
            field=models.IntegerField(default=10, verbose_name='ক্রম'),
        ),
        migrations.AlterField(
            model_name='warish',
            name='name',
            field=models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='warish',
            name='name_en',
            field=models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='warish',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.relation', verbose_name='সম্পর্ক'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.adress', verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='সনদের ধরণ'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ইমেইল(যদি থাকে)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='বাবার নাম'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='বাবার নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='ভেরিফাইড কিনা?'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='mother_name',
            field=models.CharField(max_length=100, verbose_name='মায়ের নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম (ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল নং'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ট্র্যাকিং নং'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction', verbose_name='ট্রান্সেকশন'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='warish',
            field=models.ManyToManyField(blank=True, to='certificate.warish', verbose_name='ওয়ারিশগণ'),
        ),
    ]
