# Generated by Django 5.1.5 on 2025-07-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_person_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল নং'),
        ),
    ]
