# Generated by Django 5.1.4 on 2025-10-22 16:18

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0007_person_dob_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'বৈবাহিক অবস্থা',
                'verbose_name_plural': 'বৈবাহিক অবস্থা',
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='other_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='স্বামীর নাম(বাংলায়)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='other_name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='স্বামীর নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='বর্ণনাঃ'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.maritalstatus', verbose_name='বৈবাহিক অবস্থা'),
        ),
    ]
