# Generated by Django 5.1.4 on 2025-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0008_maritalstatus_certificate_other_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='body_bg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='header_bg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='heading_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='main_body_bg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='subheading_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='title_bg',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='certificatetype',
            name='title_color',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
