# Generated by Django 5.2.8 on 2025-12-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_certificatetype_body_bg_certificatetype_header_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচয়পত্র/জন্ম নিবন্ধন'),
        ),
    ]
