# Generated by Django 5.1.4 on 2025-01-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0009_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='warishancertificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
