# Generated by Django 5.1.4 on 2025-01-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_warishancertificate_file'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='division',
        ),
        migrations.AlterField(
            model_name='adress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name=' জেলা '),
        ),
        migrations.RemoveField(
            model_name='upazilla',
            name='district',
        ),
        migrations.RemoveField(
            model_name='union',
            name='upazilla',
        ),
        migrations.AlterField(
            model_name='adress',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name=' ইউনিয়ন '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা '),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Union',
        ),
        migrations.DeleteModel(
            name='Upazilla',
        ),
    ]
