# Generated by Django 5.1.4 on 2025-01-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0011_remove_district_division_alter_adress_district_and_more'),
        ('region', '0003_postoffice_village_post_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='word_no',
        ),
        migrations.AddField(
            model_name='adress',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.word', verbose_name='ওয়ার্ড নং '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice', verbose_name='ডাকঘর '),
        ),
        migrations.AlterField(
            model_name='adress',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.village', verbose_name=' গ্রাম/মহল্লা'),
        ),
    ]
