# Generated by Django 5.1.4 on 2025-01-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0012_remove_adress_word_no_adress_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warishancertificate',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='এনআইডি-জন্ম নিবন্ধন'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='বাবার নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='মেম্বারের সুপারিশ ফাইল'),
        ),
    ]
