# Generated by Django 5.1.4 on 2025-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0013_warishancertificate_nid_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
