# Generated by Django 5.1.4 on 2025-01-22 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0014_certificatetype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warishancertificate',
            name='certificate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certificatetype', verbose_name='সনদের ধরণ'),
        ),
    ]
