# Generated by Django 5.1.4 on 2025-01-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0015_alter_warishancertificate_certificate_type'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'সনদসমূহ', 'verbose_name_plural': 'সনদসমূহ'},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name_bangla',
        ),
        migrations.AddField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম (ইংরেজিতে)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='এনআইডি-জন্ম নিবন্ধন'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='warish',
            field=models.ManyToManyField(blank=True, to='certificate.warish', verbose_name='ওয়ারিশগণ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.adress', verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.certificatetype', verbose_name='সনদের ধরণ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ইমেইল(যদি থাকে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='বাবার নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='বাবার নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='মেম্বারের সুপারিশ ফাইল'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='ভেরিফাইড কিনা?'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name',
            field=models.CharField(max_length=100, verbose_name='মায়ের নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল নং'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='tracking_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ট্র্যাকিং নং'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction', verbose_name='ট্রান্সেকশন'),
        ),
    ]
