# Generated by Django 5.1.4 on 2025-01-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0016_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='amount',
            field=models.IntegerField(default=10),
        ),
    ]
