# Generated by Django 5.1.4 on 2025-01-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0017_certificatetype_amount'),
        ('region', '0004_remove_word_union_remove_village_word_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward', verbose_name='ওয়ার্ড নং '),
        ),
    ]
