# Generated by Django 5.1.4 on 2025-01-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0018_alter_adress_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='word',
            new_name='ward',
        ),
    ]
