# Generated by Django 5.1.4 on 2025-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0019_rename_word_adress_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatetype',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='certificatetype',
            name='name_en',
            field=models.CharField(max_length=250),
        ),
    ]
