# Generated by Django 5.1.4 on 2025-01-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0022_certificate_cause_warishancertificate_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=25, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=25, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'কারণ',
                'ordering': ['serial'],
            },
        ),
    ]
