# Generated by Django 5.1.4 on 2025-01-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0023_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.cause', verbose_name='কারণঃ'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.cause', verbose_name='কারণঃ'),
        ),
    ]
