# Generated by Django 5.1.4 on 2025-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0024_alter_certificate_cause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='name',
            field=models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='name_en',
            field=models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)'),
        ),
    ]
