# Generated by Django 5.1.4 on 2025-02-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0025_alter_cause_name_alter_cause_name_en'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warish',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='warish',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='warishancertificate',
            old_name='warish',
            new_name='person',
        ),
    ]
