# Generated by Django 5.1.4 on 2025-02-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_chairman_image_chairman_signature_member_image_and_more'),
        ('certificate', '0026_rename_warish_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='caste',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='সম্প্রদায়'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.chairman', verbose_name='চেয়ারম্যান'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='আয়'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.member', verbose_name='সদস্য'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='profession',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='পেশা'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='ইমেইল(যদি থাকে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name',
            field=models.CharField(max_length=250, verbose_name='বাবার নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='বাবার নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name',
            field=models.CharField(max_length=250, verbose_name='মায়ের নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=250, verbose_name='নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='নাম (ইংরেজিতে)'),
        ),
    ]
