# Generated by Django 5.1.4 on 2025-02-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0027_certificate_caste_certificate_chairman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ভাষা'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='মন্তব্য'),
        ),
        migrations.AlterField(
            model_name='warishancertificate',
            name='language',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='ভাষা'),
        ),
    ]
