# Generated by Django 5.1.4 on 2025-02-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0028_alter_certificate_language_alter_person_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='passport',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='পাসপোর্ট নং'),
        ),
    ]
