# Generated by Django 5.1.4 on 2025-02-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0029_certificate_passport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['serial'], 'verbose_name': 'ঠিকানা', 'verbose_name_plural': 'ঠিকানা'},
        ),
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['serial'], 'verbose_name': 'কারণ', 'verbose_name_plural': 'কারণ'},
        ),
        migrations.AlterModelOptions(
            name='certificatetype',
            options={'ordering': ['name_en'], 'verbose_name': ' সনদের ধরণ', 'verbose_name_plural': ' সনদের ধরণ'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['serial'], 'verbose_name': ' ওয়ারিশ', 'verbose_name_plural': ' ওয়ারিশগণ'},
        ),
        migrations.DeleteModel(
            name='WarishanCertificate',
        ),
    ]
