# Generated by Django 5.1.4 on 2025-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0030_alter_adress_options_alter_cause_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['serial'], 'verbose_name': 'সম্পর্ক', 'verbose_name_plural': 'সম্পর্ক'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name',
            field=models.CharField(max_length=500, verbose_name='বাবার নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='father_name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='বাবার নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ভাষা'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name',
            field=models.CharField(max_length=500, verbose_name='মায়ের নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mother_name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=500, verbose_name='নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='name_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='নাম (ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='মন্তব্য'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_en',
            field=models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name_en',
            field=models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)'),
        ),
    ]
