# Generated by Django 5.1.4 on 2025-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0031_alter_relation_options_alter_certificate_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
