# Generated by Django 5.1.4 on 2025-03-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0032_certificatetype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='কারণ বর্ণনাঃ'),
        ),
    ]
