# Generated by Django 5.1.4 on 2025-03-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0033_certificate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='কারণ বর্ণনাঃ'),
        ),
    ]
