# Generated by Django 5.1.4 on 2025-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0034_alter_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='mouja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='মৌজা'),
        ),
    ]
