# Generated by Django 5.1.4 on 2025-03-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0035_adress_mouja'),
        ('region', '0007_mouja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='mouja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.mouja', verbose_name='মৌজা'),
        ),
    ]
