# Generated by Django 5.1.4 on 2025-03-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0036_alter_adress_mouja'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
