# Generated by Django 5.1.4 on 2025-03-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0037_certificate_date_certificate_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='পরিমাণ'),
        ),
    ]
