# Generated by Django 5.1.4 on 2025-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0038_certificate_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetype',
            name='template',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='amount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='পরিমাণ'),
        ),
    ]
