# Generated by Django 5.1.4 on 2025-03-16 09:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0039_certificatetype_template_alter_certificate_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='কারণ বর্ণনাঃ'),
        ),
    ]
