# Generated by Django 5.1.4 on 2025-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0040_alter_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='শিরোনাম'),
        ),
    ]
