# Generated by Django 5.1.4 on 2025-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0041_certificate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='income',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='আয়'),
        ),
    ]
