# Generated by Django 5.1.4 on 2025-03-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0042_alter_certificate_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
            ],
            options={
                'verbose_name': 'লিঙ্গ',
                'verbose_name_plural': 'লিঙ্গ',
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.gender', verbose_name='লিঙ্গ'),
        ),
    ]
