# Generated by Django 5.1.4 on 2025-03-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0043_gender_certificate_gender'),
        ('region', '0009_othersadress_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='others_adress',
            field=models.ManyToManyField(blank=True, to='region.othersadress', verbose_name='অন্যান্য এলাকাভুক্ত ঠিকানা'),
        ),
    ]
