# Generated by Django 5.1.4 on 2025-03-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0044_certificate_others_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='বিবিধ'),
        ),
    ]
