# Generated by Django 5.2 on 2025-04-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0046_certificate_memorial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/member_file/%Y', verbose_name='মেম্বারের সুপারিশ ফাইল'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='nid_file',
            field=models.FileField(blank=True, null=True, upload_to='media/nid_file/%Y', verbose_name='এনআইডি-জন্ম নিবন্ধন'),
        ),
    ]
