# Generated by Django 5.1.4 on 2025-05-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.district')),
                ('post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.postoffice')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.upazilla')),
            ],
            options={
                'verbose_name': 'ইউনিয়ন বা পৌরসভা বিবরণ',
                'verbose_name_plural': 'ইউনিয়ন বা পৌরসভা বিবরণ',
                'ordering': ['name_en'],
            },
        ),
    ]
