# Generated by Django 5.1.4 on 2025-01-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_word_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
                ('post_code', models.CharField(blank=True, max_length=15, null=True)),
                ('post_code_en', models.CharField(blank=True, max_length=15, null=True)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='village',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.postoffice'),
        ),
    ]
