# Generated by Django 5.2 on 2025-05-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_uniondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.postoffice'),
        ),
    ]
