# Generated by Django 5.1.4 on 2025-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_uniondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='lattitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='union',
            name='name_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='name_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='village',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
