# Generated by Django 5.1.4 on 2025-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_alter_district_lattitude_alter_district_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
