# Generated by Django 5.1.4 on 2025-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_member_ward'),
        ('certificate', '0018_alter_adress_word'),
        ('region', '0004_remove_word_union_remove_village_word_ward_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
