# Generated by Django 5.2 on 2025-05-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_importantlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='logo_opacity',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='monogram',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
    ]
