# Generated by Django 5.2 on 2025-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0005_uniondetails_logo_uniondetails_logo_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
