# Generated by Django 5.1.4 on 2025-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_uniondetails_logo_uniondetails_logo_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
