# Generated by Django 5.1.4 on 2025-03-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_ward_ward_no_en_alter_ward_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_en', models.CharField(max_length=25)),
                ('link', models.CharField(blank=True, max_length=15, null=True)),
                ('post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.postoffice')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.village')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.ward')),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
    ]
