# Generated by Django 5.1.4 on 2025-03-08 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_mouja'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('holding_no', models.CharField(blank=True, max_length=100, null=True, verbose_name=' হোল্ডিং নং')),
                ('village', models.CharField(blank=True, max_length=50, null=True, verbose_name=' গ্রাম/মহল্লা')),
                ('post_office', models.CharField(blank=True, max_length=50, null=True, verbose_name='ডাকঘর ')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district', verbose_name=' জেলা ')),
                ('union', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.union', verbose_name=' ইউনিয়ন ')),
                ('upazilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla', verbose_name='উপজেলা ')),
            ],
            options={
                'verbose_name': 'অন্যান্য ঠিকানা',
                'verbose_name_plural': ' অন্যান্য ঠিকানা',
                'ordering': ['serial'],
            },
        ),
    ]
