# Generated by Django 5.1.4 on 2025-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0007_uniondetails_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondetails',
            name='logo_en',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='logo_opacity_en',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='monogram_en',
            field=models.FileField(blank=True, null=True, upload_to='media/logo'),
        ),
    ]
