# Generated by Django 5.1.4 on 2025-11-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_uniondetails_logo_en_uniondetails_logo_opacity_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'ইউনিয়ন বা পৌরসভার ধরণ ',
                'verbose_name_plural': 'ইউনিয়ন বা পৌরসভার ধরণ',
                'ordering': ['serial'],
            },
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='name_short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='name_short_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uniondetails',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.district'),
        ),
        migrations.AlterField(
            model_name='uniondetails',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice'),
        ),
        migrations.AlterField(
            model_name='uniondetails',
            name='upazilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.upazilla'),
        ),
        migrations.AddField(
            model_name='uniondetails',
            name='union_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.uniontype'),
        ),
    ]
