# Generated by Django 5.1.4 on 2025-03-08 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0008_othersadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersadress',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.division', verbose_name=' বিভাগ '),
        ),
    ]
