# Generated by Django 5.1.4 on 2025-03-28 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0009_othersadress_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouja',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice'),
        ),
        migrations.AlterField(
            model_name='mouja',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.village'),
        ),
        migrations.AlterField(
            model_name='mouja',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward'),
        ),
        migrations.AlterField(
            model_name='union',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='upazilla',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice'),
        ),
        migrations.AlterField(
            model_name='village',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward'),
        ),
    ]
