# Generated by Django 5.1.4 on 2025-11-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0009_uniontype_uniondetails_name_short_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLinks',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='district',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='union_type',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='upazilla',
        ),
        migrations.DeleteModel(
            name='UnionType',
        ),
        migrations.DeleteModel(
            name='UnionDetails',
        ),
    ]
