# Generated by Django 5.2 on 2025-04-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0010_alter_mouja_post_office_alter_mouja_village_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='union',
        ),
    ]
