# Generated by Django 5.1.4 on 2025-11-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0011_importantlinks_uniontype_uniondetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantLinks',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='district',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='union_type',
        ),
        migrations.RemoveField(
            model_name='uniondetails',
            name='upazilla',
        ),
        migrations.DeleteModel(
            name='UnionType',
        ),
        migrations.DeleteModel(
            name='UnionDetails',
        ),
    ]
