# Generated by Django 5.1.4 on 2025-10-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificate', '0008_maritalstatus_certificate_other_name_and_more'),
        ('payment', '0001_initial'),
        ('region', '0008_uniondetails_logo_en_uniondetails_logo_opacity_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('name', models.CharField(max_length=500, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(max_length=500, verbose_name=' নাম(ইংরেজিতে)')),
                ('is_active', models.BooleanField(default=False, verbose_name='সক্রিয় কিনা?')),
            ],
            options={
                'verbose_name': 'হোল্ডিং টেক্সের ধরণ',
                'verbose_name_plural': 'হোল্ডিং টেক্সের ধরণসমূহ',
                'ordering': ['serial'],
            },
        ),
        migrations.CreateModel(
            name='HoldingTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10, verbose_name='ক্রম')),
                ('holding_no', models.CharField(max_length=500, verbose_name=' হোল্ডিং নাম্বার(ইংরেজিতে)')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name=' নাম(বাংলায়)')),
                ('name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name=' নাম(ইংরেজিতে)')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ইমেইল(যদি থাকে)')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='মোবাইল নং')),
                ('nid', models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র')),
                ('father_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='বাবার নাম(বাংলায়)')),
                ('father_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='বাবার নাম(ইংরেজিতে)')),
                ('mother_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='মায়ের নাম(বাংলায়)')),
                ('mother_name_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='মায়ের নাম(ইংরেজিতে)')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='পরিমান(টাকায়)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='প্রদানকৃত কিনা?')),
                ('tax_year', models.IntegerField(default=0, verbose_name='টেক্সের বছর')),
                ('adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate.adress', verbose_name='ঠিকানা')),
                ('post_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.postoffice', verbose_name='পোস্ট-অফিস')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.transaction', verbose_name='ট্রান্সেকশন')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.village', verbose_name='গ্রাম/মহল্লা')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.ward', verbose_name='ওয়ার্ড')),
                ('holding_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holdingtax.holdingtype')),
            ],
            options={
                'verbose_name': 'হোল্ডিং টেক্স',
                'verbose_name_plural': 'হোল্ডিং টেক্সসমূহ',
                'ordering': ['serial'],
            },
        ),
    ]
