# Generated by Django 5.1.4 on 2025-10-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdingtax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=10)),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
        migrations.RemoveField(
            model_name='holdingtax',
            name='tax_year',
        ),
        migrations.AddField(
            model_name='holdingtax',
            name='fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='holdingtax.fiscalyear', verbose_name='টেক্সের বছর'),
        ),
    ]
