# Generated by Django 5.1.4 on 2025-10-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdingtax', '0002_fiscalyear_remove_holdingtax_tax_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdingtype',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='holdingtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='holdingtype',
            name='is_auto_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holdingtype',
            name='is_join_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holdingtype',
            name='template',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
