# Generated by Django 5.2.8 on 2025-11-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_license_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='place_of_license',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='স্থানঃ'),
        ),
        migrations.AlterField(
            model_name='license',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='জাতীয় পরিচপত্র/জন্ম নিবন্ধন'),
        ),
    ]
