# Generated by Django 5.2.8 on 2025-12-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0010_certificatetype_is_english_alter_person_nid'),
        ('license', '0003_license_place_of_license_alter_license_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='adress_of_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='লাইসেন্সের ঠিকানা', to='certificate.adress', verbose_name='প্রতিষ্ঠানের ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='লাইসেন্স নং'),
        ),
        migrations.AlterField(
            model_name='license',
            name='place_of_license',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ব্যবসার স্থান'),
        ),
        migrations.AlterField(
            model_name='license',
            name='profession',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ব্যবসার ধরণ'),
        ),
    ]
