# Generated by Django 5.1.4 on 2025-03-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0036_alter_adress_mouja'),
        ('license', '0004_alter_license_adress_of_license'),
        ('region', '0009_othersadress_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.othersadress', verbose_name='ঠিকানা'),
        ),
        migrations.AlterField(
            model_name='license',
            name='adress_of_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adress_of_linsence', to='certificate.adress', verbose_name='প্রতিষ্ঠানের ঠিকানা'),
        ),
    ]
