# Generated by Django 5.2.8 on 2025-12-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_adress_of_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='is_auto_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='is_join_sign',
            field=models.BooleanField(default=False),
        ),
    ]
