# Generated by Django 5.1.4 on 2025-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_alter_license_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='template',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
