# Generated by Django 5.1.4 on 2025-03-18 07:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_licensetype_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='কারণ বর্ণনাঃ'),
        ),
    ]
