# Generated by Django 5.1.4 on 2025-03-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0009_alter_license_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='স্মারক নং'),
        ),
        migrations.AddField(
            model_name='license',
            name='memorial_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='স্মারক নং'),
        ),
    ]
