# Generated by Django 5.1.4 on 2025-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0010_license_license_no_license_memorial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='duration_form',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='duration_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
